# Test against the latest version of this Node.js version
environment:
  nodejs_version: "5.5.1"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js (using PowerShell)
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
